chore: Add checkbox
Wandarry/VitaNova pull request #16
Opened 2024-05-23 08:47 UTC by Wandarry

Add checkbox

<img width="160" alt="Screenshot 2024-05-23 at 10 46 45" src="https://github.com/Wandarry/VitaNova/assets/101728187/2ab0184f-e79c-4ba5-bf5d-7e2bfaa9966a">

2024-05-23 20:31 UTC, BOCOVO requested changes

2024-05-23 20:31 UTC, BOCOVO commented on .storybook/stories/Checkbox.stories.tsx
> +  title: 'uikit/CheckBox',
```suggestion
  title: 'uikit/Inputs/CheckBox',
```

2024-05-23 23:30 UTC, Wandarry commented on .storybook/stories/Checkbox.stories.tsx
> +  title: 'uikit/CheckBox',
Done @BOCOVO

2024-05-24 21:44 UTC, BOCOVO approved these changes

2024-05-24 21:44 UTC, merged