chore: Add radio button
Wandarry/VitaNova pull request #17
Opened 2024-05-23 10:07 UTC by Wandarry

Add radio button
<img width="379" alt="Screenshot 2024-05-23 at 12 06 55" src="https://github.com/Wandarry/VitaNova/assets/101728187/fc72c5be-0574-48db-ace9-b5e9e9b8cc1e">

2024-05-23 20:27 UTC, BOCOVO requested changes

2024-05-23 20:27 UTC, BOCOVO commented on .storybook/stories/RadioButton.stories.tsx
> +  title: 'uikit/RadioButton',
```suggestion
  title: 'uikit/Inputs/RadioButton',
```

2024-05-23 20:27 UTC, BOCOVO commented on components/uikit/RadioButton.tsx
Must be located in the inputs folder

2024-05-23 23:29 UTC, Wandarry commented on components/uikit/RadioButton.tsx
Done @BOCOVO

2024-05-24 21:43 UTC, BOCOVO approved these changes

2024-05-24 21:43 UTC, merged