chore: Create Login form with formik
Wandarry/VitaNova pull request #37
Opened 2024-05-28 12:36 UTC by Wandarry

Create Login form with formik

2024-05-28 13:03 UTC, BOCOVO requested changes

2024-05-28 13:03 UTC, BOCOVO commented on app/(tabs)/login.tsx
> +              // check validationSchema docs here https://formik.org/docs/guides/validation#validationschema
Remove this

2024-05-28 13:03 UTC, BOCOVO commented on app/(tabs)/login.tsx
> +  const handleLogin = () => {};
You should call the `signInWithEmail` here.
signInWithEmail is declared in `firebase/helper` directory

2024-05-29 18:40 UTC, BOCOVO commented
Can we fix this 
<img width="250" alt="image" src="https://github.com/Wandarry/VitaNova/assets/51182814/d53b33e0-8838-4662-860a-601ad0116eb8">

2024-05-30 19:29 UTC, BOCOVO commented on tsconfig.json
> +      "@firebase/auth": ["./node_modules/@firebase/auth/dist/index.rn.d.ts"]
you add this ?

2024-05-30 20:56 UTC, Wandarry commented
> Can we fix this <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/51182814/334923762-d53b33e0-8838-4662-860a-601ad0116eb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDI3ODMsIm5iZiI6MTcxNzEwMjQ4MywicGF0aCI6Ii81MTE4MjgxNC8zMzQ5MjM3NjItZDUzYjMzZTAtODgzOC00NjYyLTg2MGEtNjAxYWQwMTE2ZWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDIwNTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZDMwM2M1NzQ3NTM3MDljNjdkYWViOTQxNzA5Y2ZmNzkzMTYxNmIwMjJhOGE4OGYyNzQyZmM4NTQ5ZWU1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uVrVIHKMTJklNlDgxaayWQaAVvhHrHtktqum7HPEy2E">

J'ai essayé de passe ici @BOCOVO mais je n'y arrive pas. J'ai m'impression que la largeur est respectée à l'exception de quelques mots. Par exemple, sur mon téléphone, je n'ai pas vraiment ce problème

2024-05-31 20:53 UTC, BOCOVO commented on app/(tabs)/login.tsx
> +const initialCredential = { email: "", password: "" };
defaultValue is more understandable

2024-05-31 20:53 UTC, BOCOVO commented on app/(tabs)/login.tsx
> +    password: string;
I will suggest you to create a type for this.

2024-05-31 20:54 UTC, BOCOVO commented
> > Can we fix this <img alt="image" width="250" src="https://private-user-images.githubusercontent.com/51182814/334923762-d53b33e0-8838-4662-860a-601ad0116eb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDI3ODMsIm5iZiI6MTcxNzEwMjQ4MywicGF0aCI6Ii81MTE4MjgxNC8zMzQ5MjM3NjItZDUzYjMzZTAtODgzOC00NjYyLTg2MGEtNjAxYWQwMTE2ZWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDIwNTQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZDMwM2M1NzQ3NTM3MDljNjdkYWViOTQxNzA5Y2ZmNzkzMTYxNmIwMjJhOGE4OGYyNzQyZmM4NTQ5ZWU1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uVrVIHKMTJklNlDgxaayWQaAVvhHrHtktqum7HPEy2E">
> 
> J'ai essayé de passer ici @BOCOVO mais je n'y arrive pas. J'ai m'impression que la largeur est respectée à l'exception de quelques mots. Par exemple, sur mon téléphone, je n'ai pas vraiment ce problème


Oups, je vois.
On verra ça plus tard

2024-05-31 21:04 UTC, merged