chore: Create forgot password page
Wandarry/VitaNova pull request #39
Opened 2024-05-29 09:27 UTC by Wandarry

Create forgot password page

<img width="395" alt="Screenshot 2024-05-29 at 11 27 10" src="https://github.com/Wandarry/VitaNova/assets/101728187/c65cfe5b-0e23-4674-81bb-1c9bf19376c2">

2024-05-30 19:36 UTC, BOCOVO commented on app/(tabs)/forgotPassword.tsx
> +        <BackIconButton isDisabled={false} />
What is the default value ?

2024-05-30 19:37 UTC, BOCOVO commented on app/(tabs)/forgotPassword.tsx
> +        <Text w={"75%"} color="$black" fontWeight="$semibold" fontSize={25}>
```suggestion
        <Text w="75%" color="$black" fontWeight="$semibold" fontSize={25}>
```
also works

2024-05-30 19:39 UTC, BOCOVO requested changes

2024-05-30 19:39 UTC, BOCOVO commented on app/(tabs)/forgotPassword.tsx
> +        onPress={() => console.log("Login")}
```suggestion
        onPress={() => console.log("Send reset password request")}
```

2024-05-30 19:39 UTC, BOCOVO commented on app/(tabs)/forgotPassword.tsx
> +        isDisabled={false}
why you always add this prop 🤔  ?

2024-05-30 19:41 UTC, Wandarry commented on app/(tabs)/forgotPassword.tsx
> +        <BackIconButton isDisabled={false} />
Default value ?

2024-05-30 19:42 UTC, Wandarry commented on app/(tabs)/forgotPassword.tsx
> +        isDisabled={false}
isDisabled ?

2024-05-30 20:33 UTC, Wandarry commented
J'ai quelques questions ici @BOCOVO . A part ça, c'est bon

2024-05-31 21:01 UTC, BOCOVO commented on app/(tabs)/forgotPassword.tsx
> +        isDisabled={false}
Yes

2024-05-31 21:01 UTC, BOCOVO commented on app/(tabs)/forgotPassword.tsx
> +        <BackIconButton isDisabled={false} />
The button is disabled as default?

2024-05-31 21:02 UTC, merged