Chore/create home page
Wandarry/VitaNova pull request #41
Opened 2024-05-30 00:23 UTC by Wandarry

Create home page with its components

2024-05-30 06:34 UTC, BOCOVO requested changes

2024-05-30 06:34 UTC, BOCOVO commented on app/(tabs)/home.tsx
> +            Coucou{""} {userName} !{" "}
```suggestion
            Coucou {userName} !
```

2024-05-30 06:34 UTC, BOCOVO commented on components/pinNews.tsx
> +        <LinearGradient colors={["rgba(23,55,109,0.5)", "#081326"]}>
On peut garder que des `rgb` ou `hex` pour les couleurs ?

2024-05-30 06:34 UTC, BOCOVO commented on app/(tabs)/home.tsx
> +              newsImage={require("@/assets/images/news3.png")}
C'est la bonne image ?

2024-05-30 06:34 UTC, BOCOVO commented on components/infoCard.tsx
Les nom de composant fait du pascal case

2024-05-30 06:34 UTC, BOCOVO commented on components/infoCard.tsx
> +        <Text color="$white">Le savais-tu ?</Text>
Tu peux ajouter la nouvelle font non ?

2024-05-30 06:34 UTC, BOCOVO commented on components/infoCard.tsx
> +        alt="VitaNova"
pas de sens. qu'est-ce qu'il y a sur l'image ? C'est ce que tu dois décrire ici 😉

2024-05-30 06:34 UTC, BOCOVO commented on components/newsEventsItem.tsx
> +      <Image source={image} h={180} w={180} borderRadius={8} alt="VitaNova" />
hum ton texte alternatif là. On peut avoir quelque chose de plus précis ?

2024-05-30 07:52 UTC, Wandarry commented on components/pinNews.tsx
> +        <LinearGradient colors={["rgba(23,55,109,0.5)", "#081326"]}>
J'avais besoin du rgba pour l'opacité. Mais oui, je garde `hex` pour les couleurs

2024-05-30 07:53 UTC, Wandarry commented on app/(tabs)/home.tsx
> +              newsImage={require("@/assets/images/news3.png")}
Non, pas du tout. Puisque tout sera récupéré en ligne, j'ai ajouté une image que j'avais en local pour l'instant

2024-05-30 07:59 UTC, Wandarry commented on components/infoCard.tsx
> +        <Text color="$white">Le savais-tu ?</Text>
Oui, j'essaye ça

2024-05-30 08:01 UTC, Wandarry commented on components/infoCard.tsx
> +        alt="VitaNova"
Je sais mais je n'arrêtais pas d'avoir une erreur alors je l'ai ajouté. J'ai oublié ensuite de le retirer...Il est possible de récupérer cette info lorsque les données seront en ligne ?

2024-05-30 19:24 UTC, BOCOVO commented on app/(tabs)/home.tsx
> +              newsImage={require("@/assets/images/news3.png")}
Pourquoi ne pas mettre la bonne en même temps ?
Ce n'est pas sûr qu'on le dynamise avant lundi 😉

2024-05-30 19:24 UTC, BOCOVO commented on components/infoCard.tsx
> +        <Text color="$white">Le savais-tu ?</Text>
Ceci a donné quoi?

2024-05-30 19:25 UTC, BOCOVO commented on components/infoCard.tsx
> +        alt="VitaNova"
Oui si les stockes dans la base de donnée.

2024-05-30 19:26 UTC, BOCOVO commented on components/pinNews.tsx
> +        <LinearGradient colors={["rgba(23,55,109,0.5)", "#081326"]}>
Tu peux avoir ça aussi en hex 
`rgba(23,55,109,0.5)` => `#17376d80`

2024-05-30 19:28 UTC, Wandarry commented on components/pinNews.tsx
> +        <LinearGradient colors={["rgba(23,55,109,0.5)", "#081326"]}>
Aaah, d'accord !

2024-05-31 02:55 UTC, Wandarry commented on components/infoCard.tsx
> +        <Text color="$white">Le savais-tu ?</Text>
C'est fait !

2024-05-31 21:04 UTC, merged