chore: Create News card component
Wandarry/VitaNova pull request #60
Opened 2024-06-08 22:23 UTC by Wandarry

Create News card component

https://github.com/Wandarry/VitaNova/assets/101728187/778f1563-d042-4da9-9b44-8bd3a815bef3

2024-06-09 14:57 UTC, BOCOVO requested changes

2024-06-09 14:57 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +  data: {
Create type for this shape

2024-06-09 14:57 UTC, BOCOVO commented on app/(app)/news.tsx
> +    time: "15 min",
Pour être future proof. Mets ici `createdAt` qui sera une date au format string.
Tu te créera ensuite une fonction qui déterminera le temps écoulé. Cette fonction sera exploiter dans la carte des articles. 
Tu logera la fonction dans le dossier utils.

2024-06-09 14:57 UTC, BOCOVO commented on app/(app)/news.tsx
> +    tag: "Recherches",
Ceci n'est pas une catégorie? 
Si c'est bien tag ( mot-clé) alors ça doit être un tableau de string. Car un article peux avoir plusieurs mot-clés

2024-06-09 14:57 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +  data: {
Je vois que tu as fini par le faire ici components/newsCard.tsx

2024-06-09 14:57 UTC, BOCOVO commented on components/newsCard.tsx
> +      shadowColor="#17376D40"
Can we put this in colors ? In the gluestack.config

2024-06-09 14:57 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +          />
```suggestion
        renderItem={({ item: {id, ...item} }) => (
          <NewsCard
            {...item}
          />
```
Make life easy 😉

2024-06-09 14:57 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +          />
Dis-moi si tu ne comprends pas la syntax

2024-06-09 16:54 UTC, Wandarry commented on components/ArticlesFeed.tsx
> +  data: {
Coucou @BOCOVO, je n'ai pas trop compris ce qui est demandé ici...

2024-06-09 16:58 UTC, Wandarry commented on app/(app)/news.tsx
> +    tag: "Recherches",
En fait, je pense que c'est label qui devrait être utilisé. J'ai prévu une catégorie par news. Si je comprends bien, je dois prévoir les catégories des articles ?

2024-06-09 17:48 UTC, Wandarry commented on app/(app)/news.tsx
> +    time: "15 min",
Alors, createdAt sera de type Date ou restera en string puis la fonction s'occupera de la conversion ?

2024-06-09 19:00 UTC, BOCOVO commented on app/(app)/news.tsx
> +    time: "15 min",
Restera un string, c'est ce que tu recevra de firebase.
Dans ta fonction tu vas le convertir en date et fera en suite le calcul tu temps écoulé

2024-06-09 19:35 UTC, BOCOVO commented on app/(app)/news.tsx
> +    tag: "Recherches",
Non, pas que tu ajoutes forcément

2024-06-10 00:27 UTC, BOCOVO commented on app/(app)/news.tsx
> +    tag: "Recherches",
> J'ai prévu une catégorie par news.

Où est cette information dans la data ?

> Si je comprends bien, je dois prévoir les catégories des articles ?

Pas bien compris.

---

Les questions suivantes peuvent aider à déterminer le type de la data.
- Quelles sont les valeurs possibles ?
- Pour un article donné, la valeur de la propriété, peut-elle être plurielle ou sera-t-elle toujours singulière ?

2024-06-10 00:34 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +  data: {
Voila le code de ton type 
```ts
type ArticlesFeedProps = {
  data: {
      id: string;
      title: string;
      image: string;
      author: string;
      description: string;
      tag: string;
      time: string;
    }[];
};
```

**Commentaire**: Il est moi lisible
**Comment ?** On ne discerne pas facilement la forme de la donnée. On peut extraire le type des items de la propriété `data` ( data étant un tableau de qqc ). En gros créer un type pour ce qqc.
On a ainsi le code ci-dessous

```ts
type Article = {
      id: string;
      title: string;
      image: string;
      author: string;
      description: string;
      tag: string;
      time: string;
}

type ArticlesFeedProps = {
  data: Article[];
};
```
Remarque que `Article` ressemble à un type que tu as défini dans le fichier `components/newsCard.tsx`.
Je demandais juste de voir comment l'exploiter.

2024-06-10 00:36 UTC, BOCOVO commented on components/newsCard.tsx
> +        <Text fontFamily="Livvic_600" fontSize={15}>
Cette card , sur ton design n'a pas de author comment tu gère ce cas ?
<img width="301" alt="image" src="https://github.com/Wandarry/VitaNova/assets/51182814/b3501dcf-50be-4c09-be5f-cbb27011de4c">

2024-06-10 00:38 UTC, BOCOVO commented on components/newsCard.tsx
> +          <Icon as={Favorite} h={20} w={20} color="$primaryNormal" />
Ceci ne devrait pas être un bouton ?
Comment l'utilisateur est censé aimer l'article ?

2024-06-10 00:38 UTC, BOCOVO commented on components/newsCard.tsx
> +        <HStack alignItems="center" gap={8}>
Ceci ne devrait pas être un bouton ?
Comment l'utilisateur est censé partager l'article ?

2024-06-10 00:38 UTC, BOCOVO commented on components/newsCard.tsx
> +        <HStack alignItems="center" gap={8}>
Ceci ne devrait pas être un bouton ?
Comment l'utilisateur est censé commenter l'article ?

2024-06-10 00:40 UTC, BOCOVO commented on app/(app)/news.tsx
> +            News
Je pensais que tu devrais éviter l'anglicisme

2024-06-10 00:41 UTC, BOCOVO commented on app/(app)/news.tsx
> +          <Icon as={Search} h={28} w={28} color="$primaryNormal" />
Ce ne devrait pas être un bouton ?

2024-06-10 00:42 UTC, BOCOVO commented on app/(app)/news.tsx
Je ne vois pas ceci sur la page
<img width="218" alt="image" src="https://github.com/Wandarry/VitaNova/assets/51182814/7548acc1-5a3f-4e7f-bef4-1347185bd1d8">

2024-06-10 00:43 UTC, BOCOVO commented on components/newsCard.tsx
Enick, gardes tes noms de composant en pascal case

2024-06-10 00:44 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +import React from "react";
C'est necessaire ?

2024-06-10 00:45 UTC, BOCOVO commented on components/ArticlesFeed.tsx
> +    <Box>
Ce Box c'est nécessaire ?

2024-06-10 00:46 UTC, BOCOVO commented on components/newsCard.tsx
> +      <Image source={image} h={200} w="100%" />
can we add `alt` ?

2024-06-10 05:49 UTC, Wandarry commented on components/newsCard.tsx
> +        <Text fontFamily="Livvic_600" fontSize={15}>
Je considère qu'il y aura toutjours d'auteur

2024-06-10 05:51 UTC, Wandarry commented on app/(app)/news.tsx
Je suis dessus depuis hier...

2024-06-10 05:52 UTC, Wandarry commented on components/ArticlesFeed.tsx
> +import React from "react";
Je retire voir

2024-06-10 05:55 UTC, Wandarry commented on components/newsCard.tsx
> +        <HStack alignItems="center" gap={8}>
Depuis la card, je me disais qu'il serait possible d'uniquement voir les stats (likes, commentaires, partages) de l'article. Ce sera uniquement sur la page détail de l'article que ces `boutons` fonctionneront

2024-06-10 19:00 UTC, BOCOVO approved these changes

2024-06-18 17:52 UTC, merged